### ISSUE TITLE
🔐 Implement User Authentication (Registration, Login & Logout) 

### ISSUE THREAD

**Issue by JohnDamilola** [JohnDamilola/URL-Shortener-2.0#1]
As a User, I want to be able to do the following:

**1. Create an account (Register)**
/POST {{base_url}}/auth/register
`{
    "first_name": "",
    "last_name": "",
    "email": "",
    "password": ""
}`

**2. Authenticate (Login)**
/POST {{base_url}}/auth/login
`{
    "email": "",
    "password": ""
}`

**3. End Session (Logout)**
{{base_url}}/auth/login

**Comment by Swarangigaurkar** [comment]
Looks good to me. Can merge

**Comment by JohnDamilola** [comment]
Alright, thanks for reviewing my changes. I will merge it now.
