### ISSUE TITLE
📊 Engagement Analytics (backend)

### ISSUE THREAD

**Issue by JohnDamilola** [JohnDamilola/URL-Shortener-2.0#25]
Check more details about the API and model docs here: https://www.notion.so/URL-Shortener-App-5a0608d4ff0b4fb797e9a256cee9163d

Get all user links engagements

> GET /links/engagements
> 

<aside>
💡 return: id, 
    link_id,
    utm_source
    utm_medium 
    utm_campaign 
    utm_term 
    utm_content,
    created_on

</aside><br/><br/>

Get all engagements for a single link

> GET /links/{id}/engagements
> 

<aside>
💡 return: id, 
    link_id,
    utm_source
    utm_medium 
    utm_campaign 
    utm_term 
    utm_content,
    created_on

</aside>

**Comment by Swarangigaurkar** [comment]
created a PR for this change. can someone check it out?
