### ISSUE TITLE
🔗 Short Link Redirect to Long URL (frontend)

### ISSUE THREAD

**Issue by JohnDamilola** [JohnDamilola/URL-Shortener-2.0#26]
As a User, I want to be able to redirect from the short URL to the long original URL.

Steps to implement:
1. Fetch the long original URL by the stub
2. check if link is not disabled, password is not added,  expire_on date set is not past then redirect to the long original link
3. if link is disabled, return 404 page 
4. if password is added, show a prompt to enter the password to authenticate the link before redirection
5. if expire_on date is past, show a 404 page

**Comment by LeooHsiang** [comment]
How could I get the original URL from the stub? From our endpoint document, https://splendid-crush-9a3.notion.site/API-Endpoints-58013a6640204491858ada2541ae623a, there is no endpoint that returns that. Maybe I'm missing something here.

**Comment by JohnDamilola** [comment]
For now, use a dummy/mock response. @ksjavali is currently working on that endpoint.

Check the Link Model for the properties of the response, so you can use them in your logic (e.g. long_url, disabled, etc.)

**Comment by LeooHsiang** [comment]
Could we return a pop-up like this nstead of 404?

<img width="661" alt="image" src="https://user-images.githubusercontent.com/40188396/205186885-b0b07d22-1459-4cb5-929d-f22314bfa193.png">

**Comment by LeooHsiang** [comment]
Btw, I added a button like this for redirecting. Not sure if this is how we wanted.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/40188396/205187090-9bfd831b-6853-4046-9432-5bf5c27b548d.png">

**Comment by LeooHsiang** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/40188396/205190424-93f20a7e-19c1-4abe-abc6-29f124799cbc.png">
password prompt is added

**Comment by JohnDamilola** [comment]
> <img alt="image" width="921" src="https://user-images.githubusercontent.com/40188396/205190424-93f20a7e-19c1-4abe-abc6-29f124799cbc.png">
> 
> password prompt is added

This works! But could you fix the typo in this

**Comment by LeooHsiang** [comment]
> > <img alt="image" width="921" src="https://user-images.githubusercontent.com/40188396/205190424-93f20a7e-19c1-4abe-abc6-29f124799cbc.png">
> > password prompt is added
> 
> This works! But could you fix the typo in this

FIxed!

**Comment by JohnDamilola** [comment]
> Could we return a pop-up like this instead of 404?
> 
> <img alt="image" width="661" src="https://user-images.githubusercontent.com/40188396/205186885-b0b07d22-1459-4cb5-929d-f22314bfa193.png">

I think a 404 page is better since it is a URL redirection

Can you add this route to the App.tsx file and do something like this. This will route any other page not specified here.
<Route path="*" element={<ShortUrlRedirectionPage />} />
