### ISSUE TITLE
🔐 Enhance User Authentication implementation (frontend)

### ISSUE THREAD

**Issue by JohnDamilola** [JohnDamilola/URL-Shortener-2.0#8]
Update the base URL for the API endpoints and test the authentication implementation

New URL: https://url-shortener-server-api.herokuapp.com/

**Comment by LeooHsiang** [comment]
Working on it

**Comment by JohnDamilola** [comment]
Hi @LeooHsiang, please take a look at the comments in the pull request
https://github.com/JohnDamilola/URL-Shortener-2.0/pull/12#pullrequestreview-1183334072

**Comment by JohnDamilola** [comment]
Alright, got it!
